### DISCUSSION TITLE
Mapping firebird/etc folder to host to define custom settings

### DISCUSSION THREAD

**Discussion by petervatler** [jacobalberty/firebird-docker#111] [Q&A]
Hello,

I work on running both 2.5.x and 3.x.x Firebird engines in containers to replace local installations and speed up our development.

My current solution is to map the etc folders to my local folder but I have the following issues:

- the 2.5.9 version fails and can't start the firebird engine, even the etc folder is also missing (the 3.0.10 container works fine like this)
- the 3.0.10 version does not allow connection to databases if they weren't put into firebird/data (on 2.5.9 works fine with a custom /databases folder)

I need to be able to use a custom database storage folder and define aliases in databases/aliases config file. How to solve this with both versions?

I've also tried overwriting the the settings at database init phase and tried copying the config file to the container and updating it with a shell script - without any success.

My docker-compose.yml:

```
version: "3.8"

services:
  firebird-2.5.9:
    build:
      context: .
      dockerfile: ./2.5.9/Dockerfile
    image: "firebird-2.5.9"
    container_name: ${FIREBIRD_CONTAINER_NAME}-2.5.9
    environment:
      ISC_PASSWORD: ${ISC_PASSWORD}
      FIREBIRD_DATABASE: ${FIREBIRD_DATABASE}
      FIREBIRD_USER: ${FIREBIRD_USER}
      FIREBIRD_PASSWORD: ${FIREBIRD_PASSWORD}
    volumes:
      - ./2.5.9/databases:/databases
      - ./2.5.9/conf:/firebird/etc
    ports:
      - "3050:3050"
    restart: always
  firebird-3.0.10:
    build:
      context: .
      dockerfile: ./3.0.10/Dockerfile
    image: "firebird-3.0.10"
    container_name: ${FIREBIRD_CONTAINER_NAME}-3.0.10
    environment:
      ISC_PASSWORD: ${ISC_PASSWORD}
      FIREBIRD_DATABASE: ${FIREBIRD_DATABASE}
      FIREBIRD_USER: ${FIREBIRD_USER}
      FIREBIRD_PASSWORD: ${FIREBIRD_PASSWORD}
    volumes:
      - ./3.0.10/databases:/databases
      - ./3.0.10/conf:/firebird/etc
    ports:
      - "3051:3050"
    restart: always
```
