### ISSUE TITLE
Error pulling the image

### ISSUE THREAD

**Issue by khasburrahman** [jacobalberty/firebird-docker#31]
When I add this image to my docker-compose it returns an error 

```
...
  firebirddb:
    image: jacobalberty/firebird-docker:2.5.8-sc 
    networks: 
      - mynetwork
    volumes:
      - ./firebird-data:.firebird-data
...
```

```
Pulling firebirddb (jacobalberty/firebird-docker:2.5-sc)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
```
is this docker repo is really removed ?
