### ISSUE TITLE
How to read from curent database (gdb) file?

### ISSUE THREAD

**Issue by khasburrahman** [jacobalberty/firebird-docker#32]
Sorry I accidentally pressed enter when entering the title,
and.. I thought the comment button is to edit my post

**Comment by khasburrahman** [comment]
how can I connect to existing database?
I have the database file in `./data` with the name `MyData.GDB`
I already mount the data to `firebird/data` and the database name ex: `MyData.GDB`
```
firebirddb:
    image: jacobalberty/firebird:2.5-sc 
    networks: 
      - mynetwork
    volumes:
      - ./data:/firebird/data
    environment:
      - ISC_PASSWORD=random123
      - FIREBIRD_USER=guest
      - FIREBIRD_PASSWORD=guest
      - FIREBIRD_DATABASE=MyData.GDB
```
but when I connect with my nodeJS application it returns an error `Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login`

```
dbOptions = {
      host: 'firebirddb',
      port: '3050', 
      database: '/firebird/data/MyData.GDB',
      user: 'guest',
      password: 'guest' 
}
return Firebird.attach(dbOptions, (err, db) => {
      if (err) throw err;
      // it stops here....
}
