### ISSUE TITLE
Error when trying to connect

### ISSUE THREAD

**Issue by wwwlicious** [jacobalberty/firebird-docker#36]
I get the following error when trying to connect using docker image jacobalberty/firebird:3.0.4

`Install incomplete, please read the Compatibility chapter in the release notes for this version`

Any idea how to check what the issue might be?

**Comment by mrotteveel** [comment]
That error itself means that SRP authentication wasn't initialized, which would mean that no SYSDBA user was created. How did you launch the image?

**Comment by mrotteveel** [comment]
Looking at the entrypoint code, this may happen if you enabled legacy authentication, but are using a Firebird 3 client that tries SRP first (which is the default).

**Comment by mrotteveel** [comment]
@jacobalberty It might be advisable to also initialize a SRP user when `EnableLegacyClientAuth=true`. You could create it as SYSDBA as well, or just create a SRP user and drop it. Eg when EnableLegacyClientAuth is set, execute

```
create or alter user SYSDBA password '${ISC_PASSWORD}' using plugin Legacy_UserManager;
create or alter user SYSDBA password '${ISC_PASSWORD}' using plugin Srp;
```

instead of just

```
create or alter user SYSDBA password '${ISC_PASSWORD}';
```

**Comment by wwwlicious** [comment]
Thanks @mrotteveel for the info. 
I am launching the container using a docker compose file and was setting the `enablelegacyclientauth`.
Commenting this out resolved the problem 👍

```
version: '3'

services:

  firebird:
    image: "jacobalberty/firebird:3.0.4"
    networks:
      - test
    ports: 
      - "3050:3050"
    environment: 
     FIREBIRD_DATABASE: "test.gdb"
     FIREBIRD_USER: "test"
     ISC_PASSWORD: "pass"
     # Commenting out the line below resolved the problem 
     #EnableLegacyClientAuth: "true" 
     EnableWireCrypt: "true"
```
