### ISSUE TITLE
Firebird 4 beta 1 didn't start

### ISSUE THREAD

**Issue by Kichikahunov** [jacobalberty/firebird-docker#46]
Errors:

E: Unable to locate package libicu52
E: Unable to locate package libtommath0

**Comment by jacobalberty** [comment]
How are you launching it? docker-compose or just plain docker cli? and can i either see your command line you use to launch it or the docker-compose.yml you use?

**Comment by Kichikahunov** [comment]
**docker-compose.yml**

```
version: '3.4'

services:
   firebird4:
     build: ./firebird4
     volumes:
       - ./firebird4/databases:/firebird/data
     ports:
       - "3050:3050"
     tty: true
     environment: 
       ISC_PASSWORD: "masterk"
```

**cli:**
`docker-compose build`
